---
# tasks file for aide
- name: ensure aide package is installed 
  yum:
    name: aide
    state: present
- name: "Build and Test AIDE Database"
  shell: /usr/sbin/aide --init
  tags:
    - aide_build_database
    - medium
    - CCE-27220-3

- name: Stage AIDE Database"
  copy:
    src: /var/lib/aide/aide.db.new.gz
    dest: /var/lib/aide/aide.db.gz
    backup: yes
    remote_src: yes 
  tags:
    - aide_build_database
    - medium
    - CCE-27220-3
- name: configure periodic execution 
  template:
    src: aide_cron.j2
    dest: /etc/cron.d/aide
- name: copy aide_conf_xattrs.sh to remote machine 
  copy:
    src: aide_conf_xattrs.sh
    dest: /usr/local/bin/aide_conf_xattrs.sh
    mode: '0755'
- name: execute remote script for xattrs
  shell: /usr/local/bin/aide_conf_xattrs.sh 

- name: Cleanup remote script on remote machine 
  file: 
    path: /usr/local/bin/aide_conf_xattrs.sh
    state: absent 
  
